# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'l:\python2\task_mngr\checkpss.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 375)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #2b2b2b;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #2b2b2b;\n"
"    color: #ffffff;\n"
"    font-family: \'Segoe UI\', Arial;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3d8b40;\n"
"}\n"
"\n"
"QLineEdit, QPlainTextEdit {\n"
"    background-color: #3c3c3c;\n"
"    color: white;\n"
"    border: 2px solid #555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus, QPlainTextEdit:focus {\n"
"    border-color: #4CAF50;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    background-color: #3c3c3c;\n"
"    color: white;\n"
"    border: 2px solid #555;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pb = QtWidgets.QPushButton(self.centralwidget)
        self.pb.setGeometry(QtCore.QRect(390, 141, 75, 31))
        self.pb.setObjectName("pb")
        self.ln = QtWidgets.QLineEdit(self.centralwidget)
        self.ln.setGeometry(QtCore.QRect(251, 111, 133, 31))
        self.ln.setObjectName("ln")
        self.ln2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ln2.setGeometry(QtCore.QRect(251, 170, 133, 31))
        self.ln2.setObjectName("ln2")
        self.lbp = QtWidgets.QLabel(self.centralwidget)
        self.lbp.setGeometry(QtCore.QRect(250, 150, 81, 16))
        self.lbp.setObjectName("lbp")
        self.lbu = QtWidgets.QLabel(self.centralwidget)
        self.lbu.setGeometry(QtCore.QRect(250, 90, 81, 16))
        self.lbu.setObjectName("lbu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Who r u?"))
        self.pb.setText(_translate("MainWindow", "Sign in"))
        self.lbp.setText(_translate("MainWindow", "Password:"))
        self.lbu.setText(_translate("MainWindow", "Username:"))
